// Build a fully self-contained index.html from game.src.jsx.
//
//   - game.src.jsx           the editable game source (JSX)
//   - vendor/*.js            React, ReactDOM, Three (UMD bundles, checked in)
//   - index.html             generated, self-contained, no CDN / network deps
//
// The JSX is compiled with the CLASSIC runtime so the output is plain script
// code (no `import` statements). Inlining the libraries means the page runs the
// same online or offline and is immune to CDN/Babel version drift.
//
// Usage:  npm i @babel/standalone@7.23.10 && node build.js
const fs = require('fs');
const path = require('path');
const Babel = require('@babel/standalone');

const ROOT = __dirname;
const jsx = fs.readFileSync(path.join(ROOT, 'game.src.jsx'), 'utf8');

const compiled = Babel.transform(jsx, {
  presets: [['react', { runtime: 'classic' }]],
}).code;

const read = f => fs.readFileSync(path.join(ROOT, 'vendor', f), 'utf8');
const react = read('react.production.min.js');
const reactDom = read('react-dom.production.min.js');
const three = read('three.min.js');

// A literal </script> inside any inlined JS would close the block early.
const safe = s => s.replace(/<\/script>/gi, '<\\/script>');

const out = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<title>Goliath Grouper</title>
<style>
  html, body { margin:0; padding:0; background:#0A1220; font-family: Georgia, serif; }
  #root { width:100%; min-height:100vh; }
  #loading { color:#FFD54F; text-align:center; padding-top:40vh; font-size:18px; font-family: Georgia, serif; }
</style>
<!-- Generated by build.js — do not edit directly. Edit game.src.jsx and rebuild.
     React, ReactDOM and Three.js are inlined and the game is pre-compiled, so
     this file has no CDN/network dependencies and runs online or offline. -->
<script>/* React 18 (UMD, production) */
${safe(react)}
</script>
<script>/* ReactDOM 18 (UMD, production) */
${safe(reactDom)}
</script>
<script>/* Three.js r128 */
${safe(three)}
</script>
<script>
  window.addEventListener("error", function (e) {
    var el = document.getElementById("loading");
    if (el) {
      el.style.color = "#FF8A80"; el.style.fontSize = "13px"; el.style.padding = "12vh 16px 0";
      el.textContent = "Couldn't start the game: " + (e.message || (e.error && e.error.message) || "unknown error") + ". Please reload.";
    }
  });
</script>
</head>
<body>
<div id="root"><div id="loading">Loading Goliath Grouper...</div></div>
<script>/* Goliath Grouper — pre-compiled from game.src.jsx */
${safe(compiled)}
</script>
</body>
</html>
`;

fs.writeFileSync(path.join(ROOT, 'index.html'), out);
console.log('Built index.html:', out.length, 'bytes (', jsx.trim().split('\n').length, 'source lines )');
